// AUTO-GENERATED by scripts/generate-skill-ids.mjs — do not edit by hand.
// Regenerate after adding / renaming / deleting a skill:
//   node scripts/generate-skill-ids.mjs
// The audit check `skill-ids-module-stale` ERRORs when this file drifts
// from .claude/skills/. Name skills in app code via SKILL.<NAME> so a
// rename or deletion becomes a compile error instead of a silent stale
// string (see scripts/generate-skill-ids.mjs header for the history).

export const SKILL = {
  DEV_ADD_CHANGE: 'dev-add-change',
  DEV_ANALYZE_REPO_FOR_REVIEW: 'dev-analyze-repo-for-review',
  DEV_CACHE_PR_REVIEW_REPO: 'dev-cache-pr-review-repo',
  DEV_CLOSE_CHANGE: 'dev-close-change',
  DEV_INGEST_REPO: 'dev-ingest-repo',
  DEV_MARK_PR_READY: 'dev-mark-pr-ready',
  DEV_OPEN_PR: 'dev-open-pr',
  DEV_PR_REVIEW: 'dev-pr-review',
  DEV_PR_REVIEW_PUBLISH: 'dev-pr-review-publish',
  DEV_PULL_PR_COMMENTS: 'dev-pull-pr-comments',
  DEV_REVIEW_CHANGE: 'dev-review-change',
  DEV_REVISE_PLAN: 'dev-revise-plan',
  DEV_SETUP_REPO_IDENTITY: 'dev-setup-repo-identity',
  DEV_WRITE_CHANGE: 'dev-write-change',
  META_ADD_APP: 'meta-add-app',
  META_ADD_ARCHETYPE: 'meta-add-archetype',
  META_ADD_DOMAIN: 'meta-add-domain',
  META_ADD_ENTITY: 'meta-add-entity',
  META_ADD_MCP: 'meta-add-mcp',
  META_ADD_NOTE: 'meta-add-note',
  META_ADD_PROJECT: 'meta-add-project',
  META_ADD_RESEARCH_NOTE: 'meta-add-research-note',
  META_ADD_SCHEDULE: 'meta-add-schedule',
  META_ADD_SKILL: 'meta-add-skill',
  META_ADD_SKILL_TO_PLAYBOOK: 'meta-add-skill-to-playbook',
  META_ADD_SKILL_TO_ROUTER_VOCAB: 'meta-add-skill-to-router-vocab',
  META_APPLY_TUNING_SUGGESTION: 'meta-apply-tuning-suggestion',
  META_AUDIT: 'meta-audit',
  META_AUDIT_FOLLOWUPS: 'meta-audit-followups',
  META_BRIEF: 'meta-brief',
  META_CLOSE_PROJECT: 'meta-close-project',
  META_CURATE: 'meta-curate',
  META_DASHBOARD: 'meta-dashboard',
  META_DELETE: 'meta-delete',
  META_EVAL_SKILL_EDIT: 'meta-eval-skill-edit',
  META_EVOLVE: 'meta-evolve',
  META_MARK_RESEARCH_APPROVED: 'meta-mark-research-approved',
  META_MINE_SESSIONS: 'meta-mine-sessions',
  META_OVERSEER_REVIEW: 'meta-overseer-review',
  META_RENAME: 'meta-rename',
  META_REOPEN_PROJECT: 'meta-reopen-project',
  META_REVIEW_PROJECT_PLAN: 'meta-review-project-plan',
  META_REVISE_PROJECT_PLAN: 'meta-revise-project-plan',
  META_SCAFFOLD_PROJECT_PLAN: 'meta-scaffold-project-plan',
  META_STATUS_REPORT: 'meta-status-report',
  META_VAULT_QUERY: 'meta-vault-query',
  OS: 'os',
  RESEARCH_REVIEW: 'research-review',
  RESEARCH_REVISE: 'research-revise',
  RESEARCH_SCAFFOLD_RECOMMENDATIONS: 'research-scaffold-recommendations',
  RESEARCH_UPDATE: 'research-update',
  RESEARCH_WRITE: 'research-write',
} as const;

export type SkillId = (typeof SKILL)[keyof typeof SKILL];

export const ALL_SKILL_IDS: readonly SkillId[] = Object.values(SKILL);
