import { useEffect, useState } from 'react';

// Lazy-loaded mermaid module. Imported on first diagram render; cached after.
type MermaidApi = {
  initialize: (opts: object) => void;
  render: (id: string, source: string) => Promise<{ svg: string }>;
};

let mermaidPromise: Promise<MermaidApi> | null = null;

function loadMermaid(): Promise<MermaidApi> {
  if (!mermaidPromise) {
    mermaidPromise = import('mermaid').then((mod) => {
      const m = mod.default as unknown as MermaidApi;
      const dark =
        typeof window !== 'undefined' &&
        window.matchMedia?.('(prefers-color-scheme: dark)').matches;
      m.initialize({
        startOnLoad: false,
        theme: dark ? 'dark' : 'default',
        themeVariables: {
          fontFamily: 'system-ui, -apple-system, sans-serif',
          fontSize: '13px',
        },
        flowchart: { useMaxWidth: true, htmlLabels: true },
        sequence: { useMaxWidth: true },
      });
      return m;
    });
  }
  return mermaidPromise;
}

let renderCounter = 0;

interface Props {
  source: string;
}

export function MermaidDiagram({ source }: Props) {
  const [svg, setSvg] = useState<string>('');
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    setErr(null);
    setSvg('');
    const id = `mermaid-${++renderCounter}`;
    loadMermaid()
      .then(async (m) => {
        try {
          const result = await m.render(id, source);
          if (!cancelled) setSvg(result.svg);
        } catch (e) {
          if (!cancelled) setErr(e instanceof Error ? e.message : String(e));
        }
      })
      .catch((e) => {
        if (!cancelled) setErr(e instanceof Error ? e.message : String(e));
      });
    return () => {
      cancelled = true;
    };
  }, [source]);

  if (err) {
    return (
      <div className="mermaid-error">
        <strong>Mermaid render error</strong>
        <pre>{err}</pre>
        <details>
          <summary>Source</summary>
          <pre>{source}</pre>
        </details>
      </div>
    );
  }

  if (!svg) {
    return (
      <div className="mermaid-loading">
        <em>Rendering diagram…</em>
      </div>
    );
  }

  // SVG is generated by Mermaid (our own code path, no user content shortcuts) — safe to inject.
  // biome-ignore lint/security/noDangerouslySetInnerHtml: Mermaid produces the SVG itself
  return <div className="mermaid-diagram" dangerouslySetInnerHTML={{ __html: svg }} />;
}
